# Generated by Django 4.2.25 on 2025-10-25 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=255)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('total_victorias', models.IntegerField(default=0)),
                ('total_derrotas', models.IntegerField(default=0)),
                ('partidas_jugadas', models.IntegerField(default=0)),
                ('promedio_tiempo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nivel_mas_jugado', models.CharField(default='Básico', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jugadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=10)),
                ('tiempo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField()),
                ('jugador', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.CASCADE, to='api.jugador')),
            ],
            options={
                'db_table': 'partidas',
            },
        ),
    ]
